# -*- coding: utf-8 -*-
"""Fold the 2026-08-20 evidence into memory/reference_company_cadence.md.

9 rows rewritten (CIEN CPB DOCU GWRE KR LULU ORCL PATH TTC) + 2 new (GOLD, ZS).
Two of the rewrites are corrections of wrong "no reachable feed" claims.
"""
import io, re

p = "memory/reference_company_cadence.md"
s = io.open(p, encoding="utf-8").read()

NEW = {
"CIEN": '| CIEN | Ciena / fiscal Q3 (Aug qtr, ends ~Jul-31) | bmo | **~28d** | Advance PR titled "Ciena Announces Reporting Date and Web Broadcast for Fiscal \\<n\\> Quarter \\<yr\\> Results" — **no date in the title**, it is in the body: *"expects to announce ... on Thursday, September 3, 2026 **before the open of the U.S. financial markets**,"* broadcast 8:30am ET. FQ3-26 PR **08-06 -> release 09-03 (28d)**. Issued via BusinessWire, mirrored to the IR feed. | ⭐ **`investor.ciena.com/rss/pressrelease.aspx`** (10 items, cached 08-20). ⚠ `investors.` (plural) 301s to an SPA overview page and returns 0 items — the singular host is the one that works; `ciena.com/about/newsroom` is the old note. |',
"CPB": '| CPB | Campbells / Q4+FY (Aug-02 FY-end) & Q3 (Jun) | **bmo** | **~21d** | ⚠⚠ **The DB carried `amc` and it was wrong (corrected 08-20).** Campbells is bmo every quarter: release + slides + **pre-recorded** management remarks at **7:15am ET**, then a live Q&A at 9:00am ET — the pre-recorded format is why it never looks like a normal call. Q1 12/9, Q2 3/11, Q3 06-08, **Q4 FY26 09-03** (PR 08-13 -> 21d). Q3 lead was 05-19->06-08 (20d). | ⭐ **`investor.thecampbellscompany.com/rss/news-releases.xml`** (cached 08-20; BusinessWire-sourced). ⚠ `investor.campbellsoupcompany.com` **403s** — the old corporate name is dead as a host. |',
"DOCU": '| DOCU | Docusign / fiscal Q2 FY27 (Jul qtr) | amc | **~21d** | Thursday AMC pattern holds: *"after the U.S. markets close on Thursday, September 3, 2026,"* call 5:00pm ET. Q2 FY27 PR **08-13 16:05 -> 09-03 (21d)**. PRNewswire -> IR feed. ⚠ per-quarter IR URLs go stale; root works. | ⭐ **`investor.docusign.com/rss/pressrelease.aspx`** (cached 08-20). ⚠ `/rss/news-releases.xml` **404s on this host** — Docusign is a `pressrelease.aspx` site, not a `news-releases.xml` one. |',
"GWRE": '| GWRE | Guidewire / Q4+FY (Jul-31 FY-end) & Q3 (Apr-30 qtr) | amc | ~14-15d | Apr-30 q-end Q3: last-yr 05-22->06-03; 2026 05-20->06-04 (15d). Advance PR is titled "Guidewire to Announce \\<n\\> Quarter Fiscal Year \\<yr\\> Financial Results on \\<date\\>" — **date in the title**, readable straight off the feed. | ⚠⚠ **CORRECTED 08-20 — the old "BusinessWire only (press-center URLs 404/timeout)" note was wrong.** ⭐ **`ir.guidewire.com/rss/news-releases.xml`** works (10 items) and **demonstrably carries the advance PR** (the 05-21 Q3 advance is in it). `investor.guidewire.com` is **NXDOMAIN** — that is what the old note was really recording. |',
"KR": '| KR | Kroger / Q2 (Aug-15 qtr-end), Q1 (Jun) | bmo | **~28d** | Always BMO; release pre-open, **call 8:00am ET**. ⚠ **The advance PR names only the CALL, never the release** — title is "Kroger Announces \\<n\\> Quarter Conference Call with Investors" with **no date in the title**; the date is in the body. Q2-26 PR **08-14 16:15 -> call Fri 09-11 (28d)**. Kroger reports on a **Friday** for Q2 — do not "correct" that to a Thursday. | ⭐ **`ir.kroger.com/rss/pressrelease.aspx`** (cached 08-20). ⚠ `/rss/news-releases.xml` 404s here; the event feed is an SPA shell but PR text works. |',
"LULU": '| LULU | Lululemon / Q2 (Aug qtr), Q1 (Jun) | amc | ~14d | Release ~4:05pm ET, **call 4:30pm ET**. Advance PR is "lululemon athletica inc. announces \\<n\\> quarter fiscal \\<yr\\> earnings conference call" — **no date in the title**, body says *"will be released Thursday, September 3, 2026."* Q2-26 PR **08-20 07:30 -> 09-03 (14d)**, exactly on cadence. ⚠ per-quarter deep-link URLs go stale. | ⭐ **`corporate.lululemon.com/rss/press-releases`** (334 items, cached 08-20) — note the **`corporate.` host prefix**, a shape not in the standard probe list. Also `corporate.lululemon.com/rss` -> the **events** feed, which independently pre-lists "lululemon athletica Q2 2026 Results". `investor.lululemon.com/rss/press-releases` 301s to the same place. |',
"ORCL": '| ORCL | Oracle / Q1 FY27 (Aug qtr); Q4 (May-31 FY-end) | amc | ⚠ **exactly ~7d — metronomic** | CIK 1341439. All qtrs AMC, 4pm CT call. Advance is *"Oracle Sets the Date for its \\<n\\> Quarter Fiscal Year \\<yr\\> Earnings Announcement"*. **The 7-day lead is the tightest regular lead in this table** and it has held three straight quarters: Q2 12-02->12-10, Q3 03-03->03-10, Q4 06-01->06-10 — i.e. Oracle also **reported on the 10th three quarters running**. So a 09-10 Q1 date implies the PR lands ~09-02/09-03; **do not research ORCL earlier than that**. finnhub 09-14 (a Monday) is a weekday Oracle has not used. | ⭐ **`investor.oracle.com/rss/pressrelease.aspx`** (10 items, verified 08-20 — carries every "Sets the Date" PR). `/rss/news-releases.xml` 404s. EDGAR FTS (curl) as backup. |',
"PATH": '| PATH | UiPath / Q2 FY27 (Jul-31 qtr) | amc | **~28d** | Release *"after the market closes"*, **call 5:00pm ET** — stated verbatim in its own advance PRs, invariant. Q1 FY27 PR 04-30 -> 05-28; Q2 FY27 PR **08-06 16:10 -> 09-03 (28d)**. | ⭐ **`ir.uipath.com/news/rss`** (cached 08-20) — ⚠ **the `/news/rss` path shape**; all five standard paths (`/rss/news-releases.xml`, `/rss/pressrelease.aspx`, `/rss`, `/feed/`, `/rss/press-releases`) **404 on this host**. Listing pages are SPAs but **per-item pages render**, and events use a guessable `/events-presentations/detail/YYYYMMDD-<slug>` shape — the host 404s honestly (control probe run 08-20), so a controlled slug probe is valid here. BusinessWire mirrors the PR but **403s** this client. |',
"TTC": '| TTC | Toro / fiscal Q3 (Jul qtr), Q2 (Apr) | bmo | ~3-16d (variable) | Release ~**7:30am CT (8:30 ET)**, call 10:00am ET. Advance PR "The Toro Company to Announce Fiscal \\<yr\\> \\<n\\> Quarter Results" — **no date in the title**, body carries it. Q1 03-02->03-05 (3d); Q2 05-21->06-04 (14d); **Q3 08-18->09-03 (16d)**. Lead is genuinely variable — treat 3d as the floor. | ⚠⚠ **CORRECTED 08-20 — "BusinessWire only / invest + /news timeout" was wrong.** ⭐ **`www.thetorocompany.com/rss/news-releases.xml`** (10 items, cached 08-20); `thetorocompany.gcs-web.com/rss/news-releases.xml` serves the identical feed. **The `www.` is load-bearing** — bare `thetorocompany.com` 301s to the marketing home page and returns 0 items. |',
}

for sym, row in NEW.items():
    pat = re.compile(r"^\| " + sym + r" \|.*$", re.M)
    hits = pat.findall(s)
    assert len(hits) == 1, (sym, len(hits))
    s = pat.sub(lambda m: row, s, count=1)

GOLD = '| GOLD | Gold.com (ex-A-Mark Precious Metals) / **Q4+FY, Jun-30 FY-end** | amc | ~14-21d | ⚠ **Ticker context: this is A-Mark Precious Metals renamed** — the IR feed carries "A-Mark Precious Metals to Become Gold.com and Transfer To...". Not a new listing, not an M&A phantom. Advance PR is *"GOLD.com Sets Fiscal \\<n\\> Quarter ... Earnings Call for \\<weekday, date\\> at 4:30 p.m. ET"* — **date AND time in the title**, the cleanest shape in this table. Release lands **16:05 ET the same day** as the 4:30pm call, so amc (Q3: PR 04-15 -> "Reports Fiscal Third Quarter" 05-06 16:05, 21d; Q4 FY26: PR 08-19 -> 09-02, 14d). | ⭐ **`ir.gold.com/news-events/press-releases/rss`** (cached 08-20) — ⚠ **all five standard paths 404**; this host uses the `/news-events/press-releases/rss` shape. Its **IR calendar also pre-lists the event** at `/news-events/ir-calendar/detail/YYYYMMDD-<slug>`. |'
ZS = '| ZS | Zscaler / Q4+FY (Jul-31 FY-end) | amc | **~28d** | *"will release ... earnings **after the market closes** on Thursday, September 3, 2026,"* call **1:30pm PT**. Advance PR is "Zscaler to Host \\<n\\> Quarter Fiscal Year \\<yr\\> Earnings Conference Call" — **no date in the title**, body carries it. Q4 FY26 PR **08-06 08:00 -> 09-03 (28d)**. GlobeNewswire -> IR feed. | ⭐ **`ir.zscaler.com/rss/news-releases.xml`** (cached 08-20). ⚠ `investors.zscaler.com` is **NXDOMAIN**. |'

lines = s.split("\n")
gi = next(i for i, l in enumerate(lines) if l.startswith("| GWRE |"))
lines.insert(gi, GOLD)
last = max(i for i, l in enumerate(lines) if l.startswith("| ") and l.count("|") >= 6)
lines.insert(last + 1, ZS)
io.open(p, "w", encoding="utf-8").write("\n".join(lines))
print("cadence: 9 rows rewritten, 2 added (GOLD, ZS); table rows now",
      sum(1 for l in lines if re.match(r"^\| [A-Z]+ \|", l)))
